connectors = [
  { org = "ballerina", module = "http", version= "1.0.0", name = "Client", displayName = "Http", beta=false, category="http"},
  { org = "ballerina", module = "email", version= "0.6.0", name = "SmtpClient", displayName = "SMTP", beta=false, category="email"},
  { org = "ballerina", module = "email", version= "0.6.0", name = "PopClient", displayName = "POP3", beta=true, category="email"},
  { org = "ballerina", module = "email", version= "0.6.0", name = "ImapClient", displayName = "IMAP", beta=true, category="email"},
  { org = "ballerinax", module = "slack", version= "0.9.4", name = "Client", displayName = "Slack", beta=true, category="channel"},
  { org = "ballerinax", module = "sfdc", version= "2.1.3", name = "BaseClient", displayName = "Salesforce BaseClient", beta = true, category="salesforce"},
  { org = "ballerinax", module = "sfdc", version= "2.1.3", name = "BulkJob", displayName = "Salesforce BulkJob", beta = true, category="salesforce"},
  { org = "ballerinax", module = "github", version = "0.99.7", name = "Client", displayName = "GitHub", beta = true, category = "github"}
  { org = "ballerinax", module = "gmail", version = "0.99.2", name = "Client", displayName = "Gmail", beta = true, category = "gmail"}
]