[project]
org-name= "choreo"
version= "1.0.0"

[platform] 
target = "java8"

    [[platform.libraries]] 
    path = "./libs/choreo-workspace-langserver.jar" 
    modules = ["langserver"]

[dependencies]
