packages:
  - 'workspaces/*'
  - 'workspaces/ballerina/*'
  - 'workspaces/choreo/*'
  - 'workspaces/wso2-platform/*'
  - "workspaces/bi/*"
  - 'workspaces/common-libs/*'
  - 'workspaces/api-chat/*'
  - 'workspaces/mi/*'
