packages:
  - 'workspaces/*'
  - 'workspaces/ballerina/*'
  - 'workspaces/choreo/*'
  - "workspaces/eggplant/*"
  - 'workspaces/common-libs/*'
  - 'workspaces/api-chat/*'
  - 'workspaces/common-libs/*'
