name: 'Release vsix to github and notify'
inputs:
  repo:
    description: 'Github repository name'
    required: true
  name:
    description: 'File name'
    required: true       

runs:
  using: "composite"
  steps:
    - name: Get version
      shell: bash
      id: vsix
      run: |
        file=$(ls ${{ inputs.name }}*.vsix)
        fileName=${file#*-}
        version=${fileName%.*}
        echo "vsixName=$file" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create a release in ${{ inputs.repo }} repo
        run: |
          createResponse=`curl -X POST  -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -d '{"tag_name":"v${{ steps.vsix.outputs.version }}", \
          "draft":false, "name": "Release v${{ steps.vsix.outputs.version }}", "prerelease":true}' \
          https://api.github.com/repos/${{ inputs.repo }}/releases` \
           && id=`echo "$createResponse" | sed -n -e 's/"id":\ \([0-9]\+\),/\1/p' | head -n 1 | sed 's/[[:blank:]]//g'` && \
           uploadResponse=`curl -X POST -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -H "Content-Type:application/octet-stream" \
            --data-binary @${{ steps.vsix.outputs.vsixName }} \
            https://uploads.github.com/repos/${{ inputs.repo }}/releases/$id/assets?name=${{ steps.vsix.outputs.vsixName }}`         

    - name: "Release Notification"
      run: |
        body=$(cat << EOF
        {
          "cards": [
            { 
              "header": {
                  "title": "New Release"
              },
              "sections": [
                {
                  "widgets": [
                    {
                      "keyValue": {
                        "topLabel": "VSIX",
                        "content": "v${{ steps.vsix.outputs.version }}",
                        "onClick": {
                          "openLink": {
                            "url": "https://github.com/${{ inputs.repo }}/releases/tag/v${{ steps.vsix.outputs.version }}"
                          }
                        },
                        "iconUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/512px-Visual_Studio_Code_1.35_icon.svg.png",
                        "button": {
                          "textButton": {
                            "text": "Download VSIX",
                            "onClick": {
                              "openLink": {
                                "url": "https://github.com/${{ inputs.repo }}/releases/download/v${{ steps.vsix.outputs.version }}/${{ steps.vsix.outputs.vsixName }}"
                              }
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )
        curl \
          -X POST \
          -H 'Content-Type: application/json' \
          "https://chat.googleapis.com/v1/spaces/AAAAtkMpL8k/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=GmcsSshpc6BD68bOPu4wadJ0WjQLbDQBag3zwYPBoZ0%3D&threadKey=${{ github.run_id }}" \
          -d "$body"
