connectors = [
  { org = "ballerina", module = "http", version= "1.0.0", name = "Client", displayName = "Http"},
  { org = "ballerina", module = "email", version= "0.6.0", name = "PopClient", displayName = "POP3 Client"},
  { org = "ballerina", module = "email", version= "0.6.0", name = "ImapClient", displayName = "IMAP Client"},
  { org = "ballerina", module = "email", version= "0.6.0", name = "SmtpClient", displayName = "SMTP Client"},
  { org = "wso2", module = "twitter", version= "0.9.26", name = "Client", displayName = "Twitter"},
  { org = "ballerinax", module = "twilio", version= "0.99.0", name = "Client", displayName = "Twilio"},
  { org = "ballerinax", module = "slack", version= "0.9.1", name = "Client", displayName = "Slack"},
  { org = "ballerinax", module = "sfdc", version= "2.0.1", name = "BaseClient", displayName = "Salesforce"}
]
