parameters:
  - name: vsix_uri
    displayName: Ballerina VSIX uri
    type: string
    default: https://github.com/wso2/ballerina-plugin-vscode/releases/download/v2x-2021-11-17/ballerina.vsix
  - name: vsix_name
    displayName: Ballerina VSIX name
    type: string
    default: ballerina.vsix
  - name: low_code_editor_version
    displayName: Low Code Editor version
    type: string

resources:
  repositories:
    - repository: BALLERINA_PLUGIN_VSCODE
      type: github
      name: wso2-enterprise/ballerina-plugin-vscode
      ref: refs/heads/code-server-build
      endpoint: choreo-cicd-committer

trigger: none

pr: none

jobs:
  - job: DockerBuildandPush

    pool:
      vmImage: "ubuntu-latest"

    variables:
      - group: codeserver-cdn-group
      - name: CONTAINER_REGISTRY
        value: choreocontrolplane.azurecr.io
      - name: REPOSITORY
        value: choreoipaas/ballerina-code-server

    steps:
      - script: |
          TAG="$(date +'%Y%m%d-%H%M')"
          echo "##vso[task.setvariable variable=TAG]${TAG}"
          echo "Generated Docker tag: ${TAG}"
        displayName: "Generate Docker tag"

      - checkout: BALLERINA_PLUGIN_VSCODE
        persistCredentials: true

      - script: |
          git config --global user.email "choreo-cicd@wso2.com"
          git config --global user.name "Choreo CI Agent"
          echo "git status"
          git status
          echo "Update build.txt"
          echo "$(TAG) ${{ parameters.vsix_uri }}" >> build.txt
          git add build.txt
          git commit -m "Update build details for $(TAG)"
          git push origin HEAD:code-server-build
          git checkout origin/main
        displayName: "Update code-server-build branch new build details"

      - script: |
          node --version
          npm --version
          npm config set @wso2-enterprise:registry=https://npm.pkg.github.com
          npm install @wso2-enterprise/ballerina-low-code-editor-distribution@${{ parameters.low_code_editor_version }}
        displayName: "Install low-code module"
        env:
          NPM_ACCESS_TOKEN: $(NPM_ACCESS_TOKEN)

      - task: Docker@2
        displayName: "Build Docker image"
        inputs:
          command: build
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          Dockerfile: ".github/workflows/resources/code-server/4/Dockerfile"
          buildContext: "."
          tags: |
            latest
            $(TAG)
          arguments: "--build-arg BALLERINA_VSIX_URI=${{ parameters.vsix_uri }}  --build-arg BALLERINA_VSIX_NAME=${{ parameters.vsix_name }}"

      - task: Docker@2
        displayName: "Push Docker image"
        inputs:
          command: push
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          tags: |
            latest
            $(TAG)

      - task: CmdLine@2
        displayName: "Create Folder to download vsix"
        inputs:
          script: |
            mkdir vsix

      - task: PythonScript@0
        displayName: "Download vsix"
        inputs:
         scriptSource: inline
         script: |
          import urllib.request        
          path = r"vsix/${{ parameters.vsix_name }}"
          urllib.request.urlretrieve(${{ parameters.vsix_uri }}, path)      

      - task: ExtractFiles@1
        displayName: "Extract vsix"
        inputs:
          archiveFilePatterns: "vsix/${{ parameters.vsix_name }}"
          cleanDestinationFolder: true
          destinationFolder: "vsix/extracted"
          
      - task: AzureCLI@2
        displayName: "Upload files to CDN"
        inputs:
          azureSubscription: "choreo-codeserver-rg"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
            az storage blob upload-batch --account-name choreosharedcodeserver --source node_modules/@wso2-enterprise/ballerina-low-code-editor-distribution/build --destination codeserver/ballerina-low-code-editor-distribution@${{ parameters.low_code_editor_version }}
            az storage blob upload --account-name choreosharedcodeserver --file vsix/extracted/extension/resources/jslibs/webviewCommons.js --container-name codeserver --name ballerina-low-code-editor-distribution@${{ parameters.low_code_editor_version }}/jslibs/webviewCommons.js
