parameters:
  - name: vsix_uri
    displayName: Ballerina VSIX uri
    type: string
    default: https://github.com/wso2/ballerina-plugin-vscode/releases/download/v2x-2021-11-17/ballerina.vsix
  - name: vsix_name
    displayName: Ballerina VSIX name
    type: string
    default: ballerina.vsix

resources:
  repositories:
    - repository: BALLERINA_PLUGIN_VSCODE
      type: github
      name: wso2-enterprise/ballerina-plugin-vscode
      ref: refs/heads/code-server-build
      endpoint: choreo-cicd-committer

trigger: none

pr: none

jobs:
  - job: DockerBuildandPush

    pool:
      vmImage: "ubuntu-latest"

    variables:
      CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
      REPOSITORY: choreoipaas/ballerina-code-server

    steps:
      - script: |
          TAG="$(date +'%Y%m%d-%H%M')"
          echo "##vso[task.setvariable variable=TAG]${TAG}"
          echo "Generated Docker tag: ${TAG}"
        displayName: "Generate Docker tag"

      - checkout: BALLERINA_PLUGIN_VSCODE
        persistCredentials: true

      - script: |
          git config --global user.email "choreo-cicd@wso2.com"
          git config --global user.name "Choreo CI Agent"
          echo "git status"
          git status
          echo "Update build.txt"
          echo "$(TAG) ${{ parameters.vsix_uri }}" >> build.txt
          git add build.txt
          git commit -m "Update build details for $(TAG)"
          git push origin HEAD:code-server-build
          git checkout origin/main
        displayName: "Update code-server-build branch new build details"

      - task: Docker@2
        displayName: "Build Docker image"
        inputs:
          command: build
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          Dockerfile: ".github/workflows/resources/code-server/4/Dockerfile"
          buildContext: "."
          tags: |
            latest
            $(TAG)
          arguments: "--build-arg BALLERINA_VSIX_URI=${{ parameters.vsix_uri }}  --build-arg BALLERINA_VSIX_NAME=${{ parameters.vsix_name }}"

      - task: Docker@2
        displayName: "Push Docker image"
        inputs:
          command: push
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          tags: |
            latest
            $(TAG)
