parameters:
- name: vsix_uri
  displayName: Ballerina VSIX uri
  type: string
  default: https://github.com/wso2/ballerina-plugin-vscode/releases/download/v2x-2021-11-17/ballerina.vsix
- name: vsix_name
  displayName: Ballerina VSIX name
  type: string
  default: ballerina.vsix
- name: ballerina_dist_uri
  displayName: Ballerina distrbution deb uri
  type: string
  default: https://github.com/ballerina-platform/ballerina-distribution/releases/download/vswan-lake-beta4-rc3/ballerina-linux-installer-x64-swan-lake-beta4.deb
- name: ballerina_dist_name
  displayName: Ballerina distrbution deb name
  type: string
  default: ballerina-linux-installer-x64-swan-lake-beta4.deb

trigger: none

pr: none

jobs:
- job: DockerBuildandPush

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
    REPOSITORY: choreoipaas/ballerina-code-server

  steps:    
  - script: |
      TAG="$(date +'%Y%m%d-%H%M')"
      echo "##vso[task.setvariable variable=TAG]${TAG}"
      echo "Generated Docker tag: ${TAG}"
    displayName: 'Generate Docker tag'
    
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      Dockerfile: '.github/workflows/resources/code-server/2/Dockerfile'
      buildContext: '.'
      tags: |
        latest
        $(TAG)
      arguments: '--build-arg BALLERINA_DEB_URI=${{ parameters.ballerina_dist_uri }} --build-arg BALLERINA_DEB_NAME=${{ parameters.ballerina_dist_name }} --build-arg BALLERINA_VSIX_URI=${{ parameters.vsix_uri }}  --build-arg BALLERINA_VSIX_NAME=${{ parameters.vsix_name }}'
 
  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: push
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      tags: |
        latest
        $(TAG)
