parameters:
  - name: vsix_uri
    displayName: Ballerina VSIX uri
    type: string
    default: https://github.com/wso2/ballerina-plugin-vscode/releases/download/v2x-2021-11-17/ballerina.vsix
  - name: vsix_name
    displayName: Ballerina VSIX name
    type: string
    default: ballerina.vsix
  - name: ballerina_dist_uri
    displayName: Ballerina distrbution deb uri
    type: string
    default: https://github.com/ballerina-platform/ballerina-distribution/releases/download/vswan-lake-beta4-rc3/ballerina-linux-installer-x64-swan-lake-beta4.deb
  - name: ballerina_dist_name
    displayName: Ballerina distrbution deb name
    type: string
    default: ballerina-linux-installer-x64-swan-lake-beta4.deb

resources:
  repositories:
    - repository: BALLERINA_PLUGIN_VSCODE
      type: github
      name: wso2-enterprise/ballerina-plugin-vscode
      ref: refs/heads/code-server-build
      endpoint: choreo-cicd-committer

trigger: none

pr:
  branches:
    include:
      - "main"

jobs:
  - job: DockerBuildandPush

    pool:
      vmImage: "ubuntu-latest"

    variables:
      CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
      REPOSITORY: choreoipaas/ballerina-code-server
      BAL_VERSION:

    steps:
      - script: |
          TAG="$(date +'%Y%m%d-%H%M')"
          echo "##vso[task.setvariable variable=TAG]${TAG}"
          echo "Generated Docker tag: ${TAG}"
        displayName: "Generate Docker tag"

      - checkout: BALLERINA_PLUGIN_VSCODE
        persistCredentials: true

      - script: |
          git config --global user.email "choreo-cicd@wso2.com"
          git config --global user.name "Choreo CI Agent"
          echo "git status"
          git status
          echo "Update build.txt"
          echo "$(TAG) ${{ parameters.vsix_uri }} ${{ parameters.ballerina_dist_uri }}" >> build.txt
          git add build.txt
          git commit -m "Update build details for $(TAG)"
          git push origin HEAD:code-server-build
          git checkout origin/main
        displayName: "Update code-server-build branch new build details"

      - task: Docker@2
        displayName: "Build Docker image"
        inputs:
          command: build
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          Dockerfile: ".github/workflows/resources/code-server/2/Dockerfile"
          buildContext: "."
          tags: |
            latest
            $(TAG)
          arguments: "--build-arg BALLERINA_DEB_URI=${{ parameters.ballerina_dist_uri }} --build-arg BALLERINA_DEB_NAME=${{ parameters.ballerina_dist_name }} --build-arg BALLERINA_VSIX_URI=${{ parameters.vsix_uri }}  --build-arg BALLERINA_VSIX_NAME=${{ parameters.vsix_name }}"

      - task: Docker@2
        displayName: "Login to ACR and validate"
        inputs:
          command: login
          containerRegistry: "wso2choreo-control-plane-acr"
      - script: |
          containerID=$(docker run -d choreocontrolplane.azurecr.io/choreoipaas/ballerina-code-server:latest)
          echo $containerID
          balerinaVersion=$(docker exec "$containerID" bal -v)
          echo $balerinaVersion
          echo ls
          cd ./config/workspace
          bal new test_project_01

    # - task: Docker@2
    #   displayName: 'Push Docker image'
    #   inputs:
    #     command: push
    #     containerRegistry: 'wso2choreo-control-plane-acr'
    #     repository: $(REPOSITORY)
    #     tags: |
    #       latest
    #       $(TAG)
