trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - low-code-editor/*
pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 13.x

  - script: cd low-code-editor && npm ci
    displayName: "Install dependencies"
  - script: npm run build
    displayName: "Build"
