trigger:
  batch: true
  branches:
    include:
      - "*"

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Choreo
    displayName: Choreo Job
    timeoutInMinutes: 120

    variables:
      - group: codeserver-cdn-group

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x

      - script: |
          sudo apt-get install unzip
        displayName: "Install required dependencies"

      - script: |
          mkdir extractedDistribution
          curl -s https://api.github.com/repos/ballerina-platform/ballerina-distribution/releases | grep -wo -m1 "https.*ballerina-swan-lake-.*zip" | wget -qi - -O ballerina.zip
          unzip -qq ./ballerina.zip -d ./extractedDistribution
          rm ballerina.zip
        displayName: "Set up Ballerina"

      - script: sudo apt-get install xvfb && xvfb-run --auto-servernum ./gradlew clean build
        displayName: "Build plugin repo"
        env:
          NPM_ACCESS_TOKEN: $(NPM_ACCESS_TOKEN)
