parameters:
  - name: code_server_version
    displayName: Code server verison
    type: string
    default: 4.0.2

pr: none

trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: codeserver-cdn-group

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.18.2"

  - script: |
      yarn --version
      node --version
      npm --version
      npm install code-server@${{ parameters.code_server_version }}
    displayName: "Install code-server"
    env:
      NPM_ACCESS_TOKEN: $(NPM_ACCESS_TOKEN)

  - task: AzureCLI@2
    displayName: "Upload files to azure storage"
    inputs:
      azureSubscription: "choreo-codeserver-rg"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az storage blob upload-batch --account-name choreosharedcodeserver --source node_modules/code-server --destination codeserver/code-server@${{ parameters.code_server_version }}
