parameters:
  - name: code_server_version
    displayName: Code server verison
    type: string
    default: 4.0.2

pr: none

trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: acr-cdn-group

steps:
  - script: |
      sudo apt update && sudo apt install npm
      mkdir cdn && cd cdn
      npm init -y && npm i code-server@${{ parameters.code_server_version }}
    displayName: "Install npm"

  - task: AzureFileCopy@4
    displayName: "Upload to azure storage"
    inputs:
      azureSubscription: "choreo-code-server-cdn"
      sourcePath: node_modules/code-server
      destination: azureBlob
      containerName: codeserver/code-server@${{ parameters.code_server_version }}
      storage: choreosharedcodeserver
