trigger:
  batch: true
  branches:
    include:
      - refs/tags/v*

pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Choreo
    displayName: Choreo Job
    timeoutInMinutes: 30

    variables:
      - group: codeserver-cdn-group

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x

      - script: |
          sudo apt-get install unzip
        displayName: "Install required dependencies"

      - script: |
          mkdir extractedDistribution
          curl -s https://api.github.com/repos/ballerina-platform/ballerina-distribution/releases | grep -wo -m1 "https.*ballerina-.*swan-lake.zip" | wget -qi - -O ballerina.zip
          unzip -qq ./ballerina.zip -d ./extractedDistribution
          rm ballerina.zip
        displayName: "Set up Ballerina"

      - script: |
          INTEGRATION_TEST_RUN_ID=$(uuidgen)
        displayName: "Generate a unique ID for test run"

      - script: sudo apt-get install xvfb && xvfb-run --auto-servernum ./gradlew clean build
        displayName: "Build plugin repo"
        env:
          NPM_ACCESS_TOKEN: $(NPM_ACCESS_TOKEN)
          IS_RELEASE: true
          SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)

      - script: find . -type f -name '*.vsix' -exec sh -c 'x="{}"; mv "$x" ballerina.vsix' \;
        displayName: "Rename the vsix"

      - script: |
          createResponse=`curl -X POST  -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -d '{"tag_name":"${{ env.RELEASE_VERSION }}", \
          "draft":false, "name": "Release ${{ env.RELEASE_VERSION }}", "prerelease":true}' \
          https://api.github.com/repos/wso2/ballerina-plugin-vscode/releases` \
           && id=`echo "$createResponse" | sed -n -e 's/"id":\ \([0-9]\+\),/\1/p' | head -n 1 | sed 's/[[:blank:]]//g'` && \
           uploadResponse=`curl -X POST -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -H "Content-Type:application/octet-stream" \
            --data-binary @ballerina.vsix \
            https://uploads.github.com/repos/wso2/ballerina-plugin-vscode/releases/$id/assets?name=ballerina.vsix`
        displayName: "Create a github release"

      - script: python lcov_cobertura.py coverage/lcov.info -b src/ -o coverage/coverage.xml
        displayName: "Convert lcov to cobertura"

      - task: PublishPipelineArtifact@1
        displayName: "Publish coverage reports"
        name: PublishCoverageReports
        condition: always()
        inputs:
          targetPath: "coverage"
          artifactType: "pipeline"
          artifactName: "vscode-extension-coverage-$(INTEGRATION_TEST_RUN_ID)"

      - task: PublishCodeCoverageResults@1
        condition: always()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "coverage/coverage.xml"
