trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - syntax-tree/*
pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 13.x

  - script: cd syntax-tree && npm ci
    displayName: "Install dependencies"
  - script: cd syntax-tree && npm run build
    displayName: "Build"
