name: 'Create PR and sent notification'
inputs:
  version:
    description: 'Publish version'
    required: true 
  threadId:
    description: 'Google chat thread ID'
    required: true
runs:
  using: "composite"
  steps:
      - name: Commit version
        shell: bash
        id: commit
        run: |
          git config --global user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
          git config --global user.email ${{ secrets.BALLERINA_BOT_EMAIL }}
          git add workspaces/*/*.json
          git commit -m "Update version to v${{ inputs.version }}"
          git checkout -b "v${{ inputs.version }}"
          git remote set-url origin https://${{ secrets.BALLERINA_BOT_USERNAME }}:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git tag v${{ inputs.version }}
          git push origin "refs/heads/v${{ inputs.version }}" "refs/tags/v${{ inputs.version }}"
          pr=$(gh pr create -B main -H "v${{ inputs.version }}" --title 'Merge "v${{ inputs.version }}" into main' --body '$subject')
          echo "prURL=$pr" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}

      # - name: "PR Notification"
      #   shell: bash
      #   run: |
      #     body=$(cat << EOF
      #     {
      #       "cards": [
      #         { 
      #           "header": {
      #               "title": "New Release PR"
      #           },
      #           "sections": [
      #             {
      #               "widgets": [
      #                 {
      #                   "keyValue": {
      #                     "topLabel": "Pull Request",
      #                     "content": "${{ steps.commit.outputs.prURL }}",
      #                     "button": {
      #                       "textButton": {
      #                         "text": "Merge",
      #                         "onClick": {
      #                           "openLink": {
      #                             "url": "${{ steps.commit.outputs.prURL }}"
      #                           }
      #                         }
      #                       }
      #                     }
      #                   }
      #                 }
      #               ]
      #             }
      #           ]
      #         }
      #       ]
      #     }
      #     EOF
      #     )
      #     curl \
      #       -X POST \
      #       -H 'Content-Type: application/json' \
      #       "https://chat.googleapis.com/v1/spaces/AAAAtkMpL8k/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=GmcsSshpc6BD68bOPu4wadJ0WjQLbDQBag3zwYPBoZ0%3D&threadKey=${{ inputs.threadId }}" \
      #       -d "$body"
