name: 'Create PR and sent notification'
inputs:
  version:
    description: 'Publish version'
    required: true 
  threadId:
    description: 'Google chat thread ID'
    required: true
  bot_username:
    description: 'Ballerina bot username'
    required: true
  bot_email:
    description: 'Ballerina bot email'
    required: true
  bot_token:
    description: 'Ballerina bot token'
    required: true
  choreo:
    description: 'Is Choreo'
    type: boolean
    required: true
  ballerina:
   description: 'Is Ballerina'    
    type: boolean
    required: true
runs:
  using: "composite"
  steps:
      - name: Config git
        shell: bash
        run: |
          git config --global user.name ${{ inputs.bot_username }}
          git config --global user.email ${{ inputs.bot_email }}

      - name: Add Ballerina git changes
        if: ${{ inputs.ballerina == 'true' }}
        shell: bash
        run: git add workspaces/ballerina/*/*.json

      - name: Add Choreo git changes
        if: ${{ inputs.choreo == 'true' }}
        shell: bash
        run: git add workspaces/choreo/*/*.json

      - name: Commit version
        shell: bash
        id: commit
        run: |
          git commit -m "Update version to ${{ inputs.version }}"
          git checkout -b "${{ inputs.version }}"
          git remote set-url origin https://${{ inputs.bot_username }}:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git tag ${{ inputs.version }}
          git push origin "refs/heads/${{ inputs.version }}" "refs/tags/${{ inputs.version }}"
          pr=$(gh pr create -B main -H "${{ inputs.version }}" --title 'Merge "${{ inputs.version }}" into main' --body '$subject')
          echo "prURL=$pr" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ inputs.bot_token }}

      - name: "PR Notification"
        shell: bash
        run: |
          body=$(cat << EOF
          {
            "cards": [
              { 
                "header": {
                    "title": "New Release PR"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "keyValue": {
                          "topLabel": "Pull Request",
                          "content": "${{ steps.commit.outputs.prURL }}",
                          "button": {
                            "textButton": {
                              "text": "Merge",
                              "onClick": {
                                "openLink": {
                                  "url": "${{ steps.commit.outputs.prURL }}"
                                }
                              }
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
          )
          curl \
            -X POST \
            -H 'Content-Type: application/json' \
            "https://chat.googleapis.com/v1/spaces/AAAAtkMpL8k/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=GmcsSshpc6BD68bOPu4wadJ0WjQLbDQBag3zwYPBoZ0%3D&threadKey=${{ inputs.threadId }}" \
            -d "$body"
