FROM gradle:5.6.4-jdk8 AS build
COPY --chown=gradle:gradle . /home/gradle/project
WORKDIR /home/gradle/project
RUN gradle build --no-daemon

# FROM openjdk:8-jre-alpine
FROM adoptopenjdk/openjdk11:jre-11.0.9_11.1-alpine

RUN apk add --no-cache bash

# copy server artifacts
WORKDIR /ws-server

# COPY --from=build /home/gradle/project/build/libs/ /ws-server/
# COPY --from=build /home/gradle/project/build/dependencies/ /ws-server/
COPY ./ballerina/target/bin/ /ws-server/
COPY ./java/build/libs/ /ws-server/

EXPOSE 9090
EXPOSE 5005

CMD [ \
        "java", \
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", \
        "-Dballerina.home=/ballerina/runtime", \
        "-Dballerina.version=$(./ballerina/runtime/bin/ballerina version | head -n 1 | cut -d' ' -f2)", \
        "-cp", \
        "/ws-server/*:/ballerina/runtime/lib/tools/lang-server/lib/*:/ballerina/runtime/bre/lib/*", \
        "choreo.langserver.1_0_0.$_init" \
    ]

#    "java", \
#    "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", \ 
#    "-Dballerina.home=/ballerina/runtime", \
#    "-Dballerina.version=$(./ballerina/runtime/bin/ballerina version | head -n 1 | cut -d' ' -f2)", \
#    "-cp", \
#    '/ws-server/*:/ballerina/runtime/lib/tools/lang-server/lib/*:/ballerina/runtime/bre/lib/*' 'choreo.langserver.1_0_0.$_init'