export const SAMPLE_ICONS_GITHUB_URL = "https://raw.githubusercontent.com/wso2/integration-studio/main/SamplesForVSCode/icons/";
export const MI_COPILOT_BACKEND_URL = "https://cf3a4176-54c9-4547-bcd6-c6fe400ad0d8-dev.e1-us-east-azure.choreoapis.dev/awwr/mi-copilot-backend/mi-copilot-backend-5de/v1.0";

export const COMMANDS = {
    OPEN_PROJECT: "MI.openProject",
    OPEN_AI_PANEL: "MI.openAiPanel",
    OPEN_WELCOME: "MI.openWelcome",
    SHOW_DIAGRAM: "MI.show.diagram",
    SHOW_TASK: "MI.show.task",
    SHOW_INBOUND_ENDPOINT: "MI.show.inbound-endpoint",
    SHOW_SOURCE: "MI.show.source",
    SHOW_XML: "MI.show.xml",
    SHOW_MESSAGE_PROCESSOR: "MI.show.message-processor",
    SHOW_MESSAGE_STORE: "MI.show.message-store",
    SHOW_LOCAL_ENTRY: "MI.show.local-entry",
    SHOW_TEMPLATE: "MI.show.template",
    ADD_MEDIATOR: "MI.addMediator",
    REFRESH_COMMAND: 'MI.project-explorer.refresh',
    ADD_COMMAND: 'MI.project-explorer.add',
    ADD_API_COMMAND: 'MI.project-explorer.add-api',
    ADD_ENDPOINT_COMMAND: 'MI.project-explorer.add-endpoint',
    ADD_SEQUENCE_COMMAND: 'MI.project-explorer.add-sequence',
    ADD_INBOUND_ENDPOINT_COMMAND: 'MI.project-explorer.add-inbound-endpoint',
    ADD_PROXY_SERVICE_COMMAND: 'MI.project-explorer.add-proxy-service',
    ADD_TASK_COMMAND: 'MI.project-explorer.add-task',
    ADD_LOCAL_ENTRY_COMMAND: 'MI.project-explorer.add-local-entry',
    ADD_MESSAGE_PROCESSOR_COMMAND: 'MI.project-explorer.add-message-processor',
    ADD_MESSAGE_STORE_COMMAND: 'MI.project-explorer.add-message-store',
    ADD_TEMPLATE_COMMAND: 'MI.project-explorer.add-template',
    CREATE_PROJECT_COMMAND: 'MI.project-explorer.create-project',
    IMPORT_PROJECT_COMMAND: 'MI.project-explorer.import-project',
    REVEAL_ITEM_COMMAND: 'MI.project-explorer.revealItem',
    FOCUS_PROJECT_EXPLORER: 'MI.project-explorer.focus',
    OPEN_SERVICE_DESIGNER: 'MI.project-explorer.open-service-designer',
    OPEN_SERVICE_DESIGNER_BESIDE: 'MI.project-explorer.open-service-designer-beside',
    OPEN_PROJECT_OVERVIEW: 'MI.project-explorer.open-project-overview',
    ADD_REGISTERY_RESOURCE_COMMAND: 'MI.project-explorer.add-registry-resource',
    DELETE_REGISTERY_RESOURCE_COMMAND: 'MI.project-explorer.delete-reg-resource',
    EDIT_REGISTERY_RESOURCE_COMMAND: 'MI.project-explorer.edit-reg-resource',
    ADD_CLASS_MEDIATOR_COMMAND: 'MI.project-explorer.add-class-mediator',
    EDIT_CLASS_MEDIATOR_COMMAND: 'MI.project-explorer.edit-class-mediator',
};
