connectors = [
  { org = "wso2", module = "twitter", version= "0.9.26", name = "Client"},
  { org = "ballerina", module = "http", version= "1.0.0", name = "Client"},
  { org = "ballerina", module = "email", version= "2.0.0", name = "PopClient"},
  { org = "ballerina", module = "email", version= "2.0.0", name = "ImapClient"},
]
