import * as ConfigurableIconSvg from "./configurable-icon.svg";
import * as customSvg from "./custom.svg";
import * as DataMapperSvg from "./dataMapper.svg";
import * as defaultErrorSvg from "./default-error.svg";
import * as deleteVariableNameSvg from "./delete-variable-name.svg";
import * as DocIcon from "./doc.svg";
import * as DotBackground from "./dot-background.svg";
import * as editVariableNameSvg from "./edit-variable-name.svg";
import * as EditIcon from "./edit_icon_green.svg";
import * as emailSvg from "./email.svg";
import * as ErrorSvg from "./error.svg";
import * as ExpEditorCollapseSvg from "./exp-editor-collapse.svg";
import * as ExpEditorExpandSvg from "./exp-editor-expand.svg";
import * as fitToScreenHoverSvg from "./fit-to-screen-hover.svg";
import * as fitToScreenSvg from "./fit-to-screen.svg";
import * as formCreateSvg from "./form-create.svg";
import * as formErrorSvg from "./form-error.svg";
import * as webhookSvg from "./webhook.svg";
import * as zoomInHoverSvg from "./zoom-in-hover.svg";
import * as zoomInSvg from "./zoom-in.svg";
import * as zoomOutHoverSvg from "./zoom-out-hover.svg";
import * as zoomOutSvg from "./zoom-out.svg";

export { defaultErrorSvg };
export { formErrorSvg };
export { zoomInSvg };
export { zoomOutSvg };
export { zoomInHoverSvg };
export { zoomOutHoverSvg };
export { fitToScreenSvg };
export { fitToScreenHoverSvg };
export { deleteVariableNameSvg };
export { editVariableNameSvg };
export { formCreateSvg };
export { emailSvg };
export { webhookSvg };
export { customSvg };
export { DataMapperSvg };
export { ErrorSvg };
export { ExpEditorCollapseSvg };
export { ExpEditorExpandSvg };
export { DotBackground };
export { EditIcon };
export { ConfigurableIconSvg };
export { DocIcon };
