name: Build and run tests

on: 
  workflow_dispatch:
    inputs: 
      enableCache:
        default: true
        type: boolean

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      enableCache: ${{ inputs.enableCache }}
      isPreRelease: false
    secrets: inherit  