name: 'Cache'
description: 'Cache Rush and pnmp'
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'pnpm'

    - name: Cache Rush
      uses: actions/cache@v2
      with:
        path: |
          common/temp/install-run
          ~/.rush
        key: ${{ runner.os }}-${{ hashFiles('rush.json') }}

    - name: Cache pnpm
      uses: actions/cache@v2
      with:
        path: |
          common/temp/pnpm-store
          ~/.cache/Cypress
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        
