name: Comment Code Coverage on PR

on:
  workflow_run:
    workflows: [Test PR]
    types:
      - completed

jobs:
  comment:
    name: Add codecov comment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: CodeCoverages

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Merge reports
        run: |
          npm i -g cobertura-merge
          sed -i -e 's/\/home\/runner\/work\/ballerina\-plugin\-vscode\/ballerina-plugin-vscode\///g' lowcode-coverage.xml
          npx cobertura-merge -o output.xml package1=plugin-coverage.xml package2=lowcode-coverage.xml
      
      - name: Generate plugin code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: output.xml
          badge: true
          format: 'markdown'
          output: 'both'    

      - name: Get PR Number
        id: pr
        run: echo ::set-output name=number::$(cat number)

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.pr.outputs.number }}
          path: code-coverage-results.md   
