name: Daily Build - BI & Ballerina
on:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  Release:
    name: Release VSIX
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          fetch-depth: 2
          ref: main

      - name: Build
        uses: ./.github/actions/build
        with:
          bi: true
          ballerina: true
          API_CHAT_API_KEY: ${{ secrets.API_CHAT_API_KEY }}
          token: ${{ secrets.PUBLISH_PAT }}

      - name: Notification - Ballerina
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: Ballerina
          fileName: ballerina
          chatAPI: ${{ secrets.EGGPLANT_EXT_CHAT_API }}

      - name: Notification - Ballerina Integrator
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: Ballerina Integrator
          fileName: ballerina-integrator
          chatAPI: ${{ secrets.EGGPLANT_EXT_CHAT_API }}
