name: Daily Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Daily Mono Repo Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Ballerina
        run: |
          wget https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.1.2/ballerina-2201.1.2-swan-lake-linux-x64.deb
          sudo dpkg -i ballerina-2201.1.2-swan-lake-linux-x64.deb
      - name: Build plugin repository
        run: |
          ./gradlew clean build -x uiTest --stacktrace -scan
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
          IS_RELEASE: ${{ true }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
