name: Daily Build
on:
  schedule:
    - cron:  '30 13 * * *'

jobs:
  Build:
    name: Build and run tests
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          fetch-depth: 2
          ref: main

      - name: Build
        uses: ./.github/workflows/build.yml
        secrets: inherit

      - name: Notification - Ballerina
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: Ballerina
          fileName: ballerina
          chatAPI: ${{ secrets.EGGPLANT_EXT_CHAT_API }}

      - name: Notification - MI
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: Micro Integrator
          fileName: micro-integrator
          chatAPI: ${{ secrets.MI_TEAM_CHAT_API }}

      - name: "Failure Notification"
        if: failure()
        uses: ./.github/actions/failure-notification
        with:
          title: "Daily Build Failed"
          run_id: ${{ github.run_id }}
          chat_api: ${{ secrets.TOOLING_TEAM_CHAT_API }}
          repository: ${{ github.repository }}
