name: Daily Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Daily Mono Repo Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Setup Ballerina
        id: set-version
        run: |
          mkdir extractedDistribution
          wget https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.2.3/ballerina-2201.2.3-swan-lake.zip
          unzip -qq ./ballerina-2201.2.3-swan-lake.zip -d ./extractedDistribution
          rm ballerina-2201.2.3-swan-lake.zip
          balVersion=$(ls ./extractedDistribution)
          balHome=$(./extractedDistribution/$balVersion

          echo "::set-output name=balVersion::$balVersion"
          echo "::set-output name=balHome::$balHome"
          echo BAL_HOME=$balHome >> $GITHUB_ENV

      - name: Build plugin repository
        run: |
          ./gradlew clean build -x ui-test --stacktrace -scan
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
          IS_RELEASE: ${{ false }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          balVersion: ${{ steps.set-version.outputs.balVersion }}
          balHome: ${{ steps.set-version.outputs.balHome }}

      - name: Run UI tests
        run: |
          npx extest get-vscode -c 1.68.0 && npx extest get-chromedriver -c 1.68.0 && npx extest install-vsix -f $(ls *.vsix)
          export DISPLAY=:98.0
          Xvfb -ac :98 -screen 0 1920x1080x16 &
          npm run ui-test
