name: Daily Build - BI & Ballerina
on:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  Release:
    name: Release VSIX
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          fetch-depth: 2
          ref: main

      - name: Build
        uses: ./.github/actions/build
        with:
          bi: true
          ballerina: true
          API_CHAT_API_KEY: ${{ secrets.API_CHAT_API_KEY }}
          token: ${{ secrets.PUBLISH_PAT }}

      - name: Notification - KolaB
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: KolaB
          fileName: kolab
          api: ${{ secrets.EGGPLANT_EXT_CHAT_API }}

      - name: Notification - Kola
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: Kola
          fileName: kola-extension
          api: ${{ secrets.EGGPLANT_EXT_CHAT_API }}
