name: "Daily Publish Low Code Editor"

on:
  workflow_dispatch:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d-%H%M')"
      - run: npm version prepatch --preid=${{ steps.timestamp.outputs.timestamp }} --workspaces
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.timestamp.outputs.timestamp }}',
              sha: context.sha
            })
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - run: npm publish --tag next --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
