# Test build against daily Ballerina build
name: Draft A Release (Daily dist build)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        default: vswan-lake-preview5-snapshot
      vsix_version:
        description: Name of VSIX Asset
        required: true
        default: swan-lake-preview5-snapshot
    branches: [master]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/resources/Dockerfile
          platforms: linux/amd64
          push: false
          tags: vscode/build:latest
          build-args: |
            USERNAME=choreo-cicd
            TOKEN=${{ secrets.PUBLISH_PAT }}

  test_build:
    needs: build_docker
    name: Upload VSIX as release assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: ./gradlew clean build -x test
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
      - name: Create a release draft
        run: |
          createResponse=`curl -X POST  -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -d '{"tag_name":"${{ github.event.inputs.tag }}", \
          "draft":true, "name": "Release ${{ github.event.inputs.vsix_version }}", "prerelease":true}' \
          https://api.github.com/repos/wso2-enterprise/ballerina-plugin-vscode/releases` \
           && id=`echo "$createResponse" | sed -n -e 's/"id":\ \([0-9]\+\),/\1/p' | head -n 1 | sed 's/[[:blank:]]//g'` && \
           uploadResponse=`curl -X POST -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -H "Content-Type:application/octet-stream" \
            --data-binary @ballerina-${{ github.event.inputs.vsix_version }}.vsix \
            https://uploads.github.com/repos/wso2-enterprise/ballerina-plugin-vscode/releases/$id/assets?name=ballerina-${{ github.event.inputs.vsix_version }}.vsix`
