# Test build against released Ballerina distribution, skipping test run
name: Draft A Release (Without tests)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        default: vswan-lake-preview5-snapshot
      vsix_version:
        description: Name of VSIX Asset
        required: true
        default: swan-lake-preview5-snapshot
    branches: [master]

jobs:
  build:
    name: Creat a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build repository without tests
        run: ./gradlew clean build -x test
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
      - name: Create a release draft
        run: |
          createResponse=`curl -X POST  -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -d '{"tag_name":"${{ github.event.inputs.tag }}", \
          "draft":true, "name": "Release ${{ github.event.inputs.vsix_version }}", "prerelease":true}' \
          https://api.github.com/repos/prabushi/ballerina-plugin-vscode/releases` \
           && id=`echo "$createResponse" | sed -n -e 's/"id":\ \([0-9]\+\),/\1/p' | head -n 1 | sed 's/[[:blank:]]//g'` && \
           uploadResponse=`curl -X POST -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -H "Content-Type:application/octet-stream" \
            --data-binary @ballerina-${{ github.event.inputs.vsix_version }}.vsix \
            https://uploads.github.com/repos/prabushi/ballerina-plugin-vscode/releases/$id/assets?name=ballerina-${{ github.event.inputs.vsix_version }}.vsix`
