# Build and push the code server image using the Ballerina distribution of the latest daily build and the latest git released VSIX.
name: Daily Code Server Image 3

on:
  workflow_dispatch:
    branches: [master]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d.%H%M')"
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/resources/code-server/3/Dockerfile
          platforms: linux/amd64
          push: true
          tags: prabushi/lowcode-code-server:0.${{ steps.date.outputs.date }}
          build-args: |
            GIT_PAT: ${{ secrets.PUBLISH_PAT }}
