# Test build against released Ballerina distributions in the website
name: Publish Codecov (Released dist)

on:
  workflow_dispatch:
    inputs:
      bal_dist_version:
        description: Version of Ballerina distribution
        required: true
        default: swan-lake-preview5
    branches: [master]

jobs:
  build:
    name: Publish codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - run: mkdir extractedDistribution
      - run: sudo apt-get install unzip
      - name: Download ballerina distribution
        run: curl http://dist-dev.ballerina.io/downloads/${{ github.event.inputs.bal_dist_version }}/ballerina-${{ github.event.inputs.bal_dist_version }}.zip --output ballerina-${{ github.event.inputs.bal_dist_version }}.zip
      - run: unzip -qq ./ballerina-${{ github.event.inputs.bal_dist_version }}.zip -d ./extractedDistribution
      - run: rm ballerina-${{ github.event.inputs.bal_dist_version }}.zip
      - name: Build repository with tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew clean build
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
      - name: Publish codecov report
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
