# Publish the extension to marketplace
name: Publish VSCode Extension

on:
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    name: Package and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.CHOREO_BOT_TOKEN }}
      - run: npm install -g vsce
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.CHOREO_BOT_TOKEN }}
      - run: vsce package
      - run: vsce publish -p ${{ secrets.EXTENSION_PUBLISH_TOKEN }}
