# Build and push the code server image 
name: Daily Code Server Image

on:
  workflow_dispatch:
    inputs:
      redirect:
        description: Redirect Choreo URI
        required: true
        default: https://consolev2.preview-dv.choreo.dev/
    branches: [main]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/resources/code-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: prabushi/code-server:latest
          build-args: |
            REDIRECT_URI=${{ github.event.inputs.redirect }}

