# Publish the extension to marketplace
name: Publish VSCode Extension

on:
  workflow_dispatch:
    inputs:
      vsix_version:
        description: VSIX Release Version
        required: true
        default: 2.0.0-beta1
    branches: [master]

jobs:
  build:
    name: Package and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g vsce
      - run: ./gradlew clean build -x test
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
      - run: vsce package
      - name: Publish the extension
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath ballerina-${{ github.event.inputs.vsix_version }}.vsix
