# Create a plugin release without running tests.
# This release updates the npm dependencies (doesn't honor the package-lock file ).
name: Release Without Tests

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    name: Create a release for VS Code extension without running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Update npm dependencies
        run: npm update @wso2-enterprise/ballerina-low-code-editor-distribution @wso2-enterprise/ballerina-configurable-editor @wso2-enterprise/ballerina-low-code-edtior-commons
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
      - name: Build repository without tests
        run: sudo apt-get install xvfb && xvfb-run --auto-servernum ./gradlew clean build -x test
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
      - run: find . -type f -name '*.vsix' -exec sh -c 'x="{}"; mv "$x" ballerina.vsix' \;
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"
      - name: Create a release in wso2/ballerina-plugin-vscode repo
        run: |
          createResponse=`curl -X POST  -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -d '{"tag_name":"v2x-${{ steps.date.outputs.date }}", \
          "draft":false, "name": "Release 2x-${{ steps.date.outputs.date }}", "prerelease":true}' \
          https://api.github.com/repos/wso2/ballerina-plugin-vscode/releases` \
           && id=`echo "$createResponse" | sed -n -e 's/"id":\ \([0-9]\+\),/\1/p' | head -n 1 | sed 's/[[:blank:]]//g'` && \
           uploadResponse=`curl -X POST -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -H "Content-Type:application/octet-stream" \
            --data-binary @ballerina.vsix \
            https://uploads.github.com/repos/wso2/ballerina-plugin-vscode/releases/$id/assets?name=ballerina.vsix`
