name: Save build cache when PR merged

on:
  push

env:
  ballerina_version: 2201.3.1

jobs:
  Build_Stage:
    name: Build repo
    if: github.event.pull_request.merged
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: gigara/rush-cache@v1
        with:
          pnpm: 7.26.3
          node: 16.x
          set-env: true
          rush-install: true

      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: ${{ env.ballerina_version }}

      - name: Build repo and save cache
        run: node common/scripts/install-run-rush.js build --verbose
