name: Test PR

on: 
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build.yml
    secrets: inherit  
    