name: Test PR

on: 
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ballerina_version: 2201.2.3
  ballerina_zip_url: https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.2.3/ballerina-2201.2.3-swan-lake.zip
  ballerina_deb_url: https://dist.ballerina.io/downloads/2201.2.3/ballerina-2201.2.3-swan-lake-linux-x64.deb
  vscVersion: 1.68.0

jobs:
  Build:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build.yml
    secrets: inherit  
    