# Test build without tests
name: Test PR

on:
    pull_request:
        branches: [master]

jobs:
    test_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: ./gradlew clean build -x test
              env:
                  NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
