name: Run UI tests

on: 
  workflow_dispatch:

jobs:
  Build:
    name: Build repo
    timeout-minutes: 45
    runs-on: ubuntu-latest
    outputs:
      runBalPluginTests: ${{ steps.testMatrix.outputs.runBalPluginTests }}
      testArray: ${{ steps.testMatrix.outputs.testArray }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          fetch-depth: 2

      - name: Build
        uses: ./.github/actions/build
        with:
          isPreRelease: ${{ inputs.isPreRelease }}
          enableCache: ${{ inputs.enableCache }}
          ballerina: ${{ inputs.ballerina }}
          choreo: ${{ inputs.choreo }}
          version: ${{ inputs.version }}

  UiTest_Choreo:
    name: Integration Tests
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Restore build
        uses: actions/download-artifact@v3
        with:
          name: PluginBuild
          path: ./

      - name: Set up workspace
        run: |
          unzip build.zip
          rm build.zip

      - name: Setup
        uses: gigara/rush-cache@v1
        with:
          pnpm: 7.26.3
          node: 16.x
          rush-install: true

      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: ${{ env.ballerina_version }}

      - name: install packages
        run: |
          sudo apt-get install ffmpeg
          sudo apt-get install xvfb
          sudo apt-get install -y gnome-keyring
          sudo apt-get install libsecret-1.0
          sudo apt install dbus-x11

      - name: Run tests
        run: |
          cd workspaces/choreo-extension 
          pnpm run extest-setup
          export $(dbus-launch)
          export DISPLAY=:98.0
          Xvfb -ac :98 -screen 0 1920x1080x16 & pnpm run e2e-test
        env:
          TEST_IDP_USERNAME: e8085eae-9391-4d03-9302-672068c1fe50
          TEST_IDP_PASSWORD: ${{ secrets.TEST_IDP_PASSWORD }}
          TEST_USER_ORG_HANDLE: choreouser
          TEST_USER_ORG_ID: 3678
          TEST_USER_ORG_UUID: 9f3f5ca2-c1f2-43e7-afbe-a15714138b57
          TEST_GITHUB_USERNAME: choreo-test-user@wso2.com
          TEST_GITHUB_PAT: ${{ secrets.TEST_GITHUB_PAT }}
          APIM_CLIENT_ID: ciwnWuwZfbcdzBUcnkhKvi_mcBUa
          APIM_TOKEN_URL: https://sts.choreo.dev/oauth2/token
          CLIENT_ID: aVKhTSUMu_QfEwmCtrcuWoLy92oa
          LOGIN_URL: https://console.choreo.dev/login
          REDIRECT_URL: https://console.choreo.dev/vscode-auth
          TOKEN_URL: https://api.asgardeo.io/t/a/oauth2/token
          VSCODE_CLIENT_ID: GWj5MzWNrOB28jX_wu5ZGu7I1VIa
          PROJECT_API: https://apis.choreo.dev/projects/1.0.0/graphql
          APIM_SCOPES: urn:choreosystem:componentsmanagement:component_create

      - name: Publish UI Test recording
        uses: actions/upload-artifact@v3
        with:
          path: workspaces/choreo-extension/test-resources/ui-test-out.mp4
          name: Integration-test-recording-${{ github.run_attempt }}
        if: failure()

      - name: Publish UI Test Screenshots
        uses: actions/upload-artifact@v3
        with:
          path: workspaces/choreo-extension/test-resources/screenshots/
          name: Integration-test-screenshots-${{ github.run_attempt }}
        if: failure()

  UiTest_Ballerina:
    name: Run UI tests
    needs: Build_Stage
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Restore build
        uses: actions/download-artifact@v3
        with:
          name: PluginBuild
          path: ./

      - name: Set up workspace
        run: |
          unzip build.zip
          rm build.zip

      - name: Setup
        uses: gigara/rush-cache@v1
        with:
          pnpm: 7.26.3
          node: 16.x
          rush-install: true

      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: ${{ env.ballerina_version }}

      - name: Run tests
        run: |
          cd workspaces/ballerina-extension
          sudo apt-get install xvfb
          pnpm run ui-test-setup
          export DISPLAY=:98.0
          Xvfb -ac :98 -screen 0 1920x1080x16 & pnpm run ui-test

      - name: Publish UI Test Screenshots
        uses: actions/upload-artifact@v3
        with:
          path: workspaces/ballerina-extension/test-resources/screenshots/
          name: Ui-test-screenshots-${{ github.run_attempt }}
        if: failure()
