name: Run UI tests

on: 
  workflow_dispatch:

jobs:
  Test:
    name: Integration Tests
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          fetch-depth: 2
  
      - name: Build
        uses: ./.github/actions/build

      - name: install packages
        run: |
          sudo apt-get install ffmpeg
          sudo apt-get install xvfb
          sudo apt-get install -y gnome-keyring
          sudo apt-get install libsecret-1.0
          sudo apt install dbus-x11

      - name: run tests
        run: |
          cd workspaces/choreo-extension 
          pnpm run extest-setup
          export $(dbus-launch)
          export DISPLAY=:98.0
          Xvfb -ac :98 -screen 0 1920x1080x16 & pnpm run e2e-test
        env:
          TEST_IDP_USERNAME: e8085eae-9391-4d03-9302-672068c1fe50
          TEST_IDP_PASSWORD: ${{ secrets.TEST_IDP_PASSWORD }}
          TEST_USER_ORG_HANDLE: choreouser
          TEST_GITHUB_USERNAME: choreo-test-user@wso2.com
          TEST_GITHUB_PAT: ${{ secrets.TEST_GITHUB_PAT }}
          TEST_GITHUB_ORG: choreo-test-apps
          TEST_GITHUB_MONO_REPO: vscode-ext-mono-repo-tests-prod

      - name: Publish UI Test recording
        uses: actions/upload-artifact@v3
        with:
          path: workspaces/choreo-extension/test-resources/ui-test-out.mp4
          name: Integration-test-recording-${{ github.run_attempt }}
        if: failure()

      - name: Publish UI Test Screenshots
        uses: actions/upload-artifact@v3
        with:
          path: workspaces/choreo-extension/test-resources/screenshots/
          name: Integration-test-screenshots-${{ github.run_attempt }}
        if: failure()
